Repository hyeonjiroh/Taskify, pull requests merged in 2025-03, with the labels that each got.

#7 docs: Update README.md
  README.md
Labels: docs

#9 chore: #0/PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#10 docs: Update README.md
  README.md
Labels: docs

#12 chore: #11/폰트 & 컬러 시스템 설정
  app/fonts/GeistMonoVF.woff
  app/fonts/GeistVF.woff
  app/globals.css
  app/layout.tsx
  app/page.tsx
  docs/STYLE_GUIDE.md
  tailwind.config.ts
Labels: chore

#24 feat: #13/breakpoint 설정 및 윈도우 사이즈 감지 훅 생성
  .eslintrc.json
  app/utils/breakpoints.ts
  hooks/useWindowSize.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feat

#26 [docs] #0/STYLE_GUIDE.md 수정
  docs/STYLE_GUIDE.md
Labels: docs

#30 feat: #23/기본 버튼 컴포넌트 구현
  app/components/common/button/Button.tsx
  app/components/common/button/buttonStyles.tsx
Labels: feat

#34 chore: #33/폴더 구조 변경 및 절대 경로 alias 설정
  README.md
  app/utils/breakpoints.ts
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/buttonStyles.tsx
  src/constants/breakpoint.ts
  src/hooks/useWindowSize.ts
  tsconfig.json
Labels: refactor, docs, chore

#36 chore: #0/tailwind.config.ts & STYLE_GUIDE.md 수정
  docs/STYLE_GUIDE.md
  tailwind.config.ts
Labels: docs, chore

#37 feat: #0/폴더 구조 변경
  package-lock.json
  package.json
  public/icon/add_box.svg
  public/icon/crown.svg
  public/logo/logo_large.svg
  public/logo/logo_small.svg
  src/app/(after-login)/dashboard/[dashboardid]/edit/page.tsx
  src/app/(after-login)/dashboard/[dashboardid]/layout.tsx
  src/app/(after-login)/dashboard/[dashboardid]/page.tsx
  src/app/(after-login)/layout.tsx
  src/app/(after-login)/mydashboard/page.tsx
  src/app/(after-login)/mypage/page.tsx
  src/app/(before-login)/(with-navbar)/layout.tsx
  src/app/(before-login)/(with-navbar)/page.tsx
  src/app/(before-login)/(without-navbar)/login/page.tsx
  src/app/(before-login)/(without-navbar)/signup/page.tsx
  src/app/favicon.ico
  src/components/common/pagenation-button/PagenationButton.tsx
  src/components/layout/sidebar/SideMenuItem.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/lib/constants/breakpoint.ts
  src/lib/hooks/useWindowSize.ts
  src/lib/store/useDashboardStore.ts
  tailwind.config.ts
Labels: feat

#38 feat: #27/유저 아이콘 버튼 생성
  src/components/common/user-icon/UserIcon.tsx
Labels: feat

#40 feat: #20/사이드 바 레이아웃 & 일부 기능 구현
  src/app/(after-login)/dashboard/[dashboardid]/layout.tsx
  src/components/layout/sidebar/SideMenuItem.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/lib/hooks/useDashboardStore.ts
  src/lib/types.ts
  src/lib/utils/colorUtils.ts
Labels: design, feat

#41 feat: #31/ 공용 컴포넌트 Input 구현
  package-lock.json
  package.json
  public/icon/calendar_icon.svg
  public/icon/visibility_icon.svg
  public/icon/visibility_off_icon.svg
  src/components/common/input/Input.tsx
  src/components/common/input/inputStyles.tsx
  src/components/common/input/usePasswordVisibility.tsx
Labels: design, feat

#43 refactor: #42/공통 컴포넌트 생성 및 사이드 바 컴포넌트 분리
  src/components/common/logo-button/LogoButton.tsx
  src/components/common/modal/Modal.tsx
  src/components/layout/sidebar/AddButton.tsx
  src/components/layout/sidebar/SideMenuItem.tsx
  src/components/layout/sidebar/Sidebar.tsx
Labels: refactor

#48 refactor: #46/로고 버튼 네비게이팅 기능 변경
  src/components/common/logo-button/LogoButton.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/lib/hooks/useDashboardStore.ts
  src/lib/utils/colorUtils.ts
Labels: refactor

#47 refactor: #44 버튼 컴포넌트 리팩토링
  src/components/common/button/Button.tsx
  src/components/common/button/buttonStyles.tsx
Labels: refactor

#49 [feat] #21/모달 공통 컴포넌트 & 사이드 바에 대시보드 생성 모달 연결
  package-lock.json
  package.json
  public/icon/add_box_icon.svg
  public/icon/close_icon.svg
  public/icon/crown_icon.svg
  public/icon/menu_icon.svg
  src/app/(after-login)/layout.tsx
  src/app/layout.tsx
  src/components/common/modal/CancelButton.tsx
  src/components/common/modal/CloseButton.tsx
  src/components/common/modal/MenuButton.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/SubmitButton.tsx
  src/components/layout/sidebar/AddButton.tsx
  src/components/layout/sidebar/SideMenuItem.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/create-dashboard/CreateDashboardModal.tsx
  src/components/modal/create-task/CreateTaskModal.tsx
  src/components/modal/edit-task/EditTaskModal.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/components/modal/invite/InviteModal.tsx
  src/components/modal/task-detail/TaskDetail.tsx
  src/lib/constants/breakpoint.ts
  src/lib/hooks/useCheckViewport.ts
  src/lib/hooks/useDashboardStore.ts
  src/lib/hooks/useGetViewport.ts
  src/lib/hooks/useModalStore.ts
  tailwind.config.ts
Labels: design, feat

#52 refactor: #32/모달 컴포넌트 리팩토링 및 Alert 컴포넌트 생성
  src/app/(after-login)/layout.tsx
  src/app/(before-login)/(without-navbar)/layout.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/color-palette/ColorPalette.tsx
  src/components/common/modal/CancelButton.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/SubmitButton.tsx
  src/components/layout/sidebar/AddButton.tsx
  src/components/layout/sidebar/SideMenuItem.tsx
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/create-dashboard/CreateDashboardModal.tsx
  src/components/modal/create-task/CreateTaskModal.tsx
  src/components/modal/edit-task/EditTaskModal.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/components/modal/invite/InviteModal.tsx
  src/components/modal/task-detail/TaskDetail.tsx
  src/lib/hooks/useAlertStore.ts
  src/lib/hooks/useCheckViewport.ts
Labels: refactor, design, feat

#54 feat: #53/대시보드 상세 페이지 컬럼 레이아웃
  public/icon/add_icon.svg
  public/icon/setting_icon.svg
  src/app/(after-login)/dashboard/[dashboardid]/_components/AddColumnButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/AddTaskButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/DashboardColumn.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/EditColumnButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/page.tsx
  src/app/(after-login)/layout.tsx
  src/components/common/modal/CloseButton.tsx
  src/components/common/modal/MenuButton.tsx
  src/components/common/modal/Modal.tsx
  src/components/layout/sidebar/AddButton.tsx
  src/lib/types.ts
Labels: refactor, design, feat

#57 refactor: #55/모달 컴포넌트 & Alert 컴포넌트 리팩토링
  src/app/(after-login)/layout.tsx
  src/app/(before-login)/(without-navbar)/layout.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/alert/AlertProvider.tsx
  src/components/common/alert/alertData.ts
  src/components/common/logo-button/LogoButton.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalProvider.tsx
  src/components/common/modal/modalData.ts
  src/components/layout/sidebar/SideMenuItem.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/create-dashboard/CreateDashboardModal.tsx
  src/components/modal/create-task/CreateTaskModal.tsx
  src/components/modal/edit-task/EditTaskModal.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/components/modal/invite/InviteModal.tsx
  src/components/modal/task-detail/TaskDetail.tsx
  src/lib/hooks/useCheckViewport.ts
  src/lib/hooks/useGetViewport.ts
Labels: refactor

#61 feat: #58/상단 네비게이션 바 레이아웃
  public/icon/check_icon.svg
  src/app/(after-login)/dashboard/[dashboardid]/_components/AddColumnButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/AddTaskButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/EditColumnButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/layout.tsx
  src/app/(after-login)/layout.tsx
  src/app/(after-login)/mydashboard/layout.tsx
  src/app/(after-login)/mypage/layout.tsx
  src/app/(before-login)/(with-navbar)/layout.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/alert/AlertProvider.tsx
  src/components/common/button/buttonStyles.tsx
  src/components/common/color-palette/ColorPalette.tsx
  src/components/common/logo-button/LogoButton.tsx
  src/components/common/modal/CloseButton.tsx
  src/components/common/modal/MenuButton.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalProvider.tsx
  src/components/common/user-icon/UserIcon.tsx
  src/components/layout/navbar/DashboardMenu.tsx
  src/components/layout/navbar/MemberIcon.tsx
  src/components/layout/navbar/MemberList.tsx
  src/components/layout/navbar/UserMenu.tsx
  src/components/layout/sidebar/AddButton.tsx
  src/components/layout/sidebar/SideMenuItem.tsx
  src/lib/constants/breakpoints.ts
  src/lib/constants/route.ts
  src/lib/hooks/useCheckViewport.ts
  src/lib/store/useAlertStore.ts
  src/lib/store/useDashboardStore.ts
  src/lib/store/useModalStore.ts
  src/lib/types.ts
Labels: design, feat

#62 feat: #60/사이드 바 API 연결
  src/app/(after-login)/layout.tsx
  src/components/layout/sidebar/AddButton.tsx
  src/components/layout/sidebar/SideMenuHeader.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/layout/sidebar/index.tsx
  src/lib/apis/dashboard.ts
  src/lib/constants/tokens.ts
  src/lib/constants/urls.ts
Labels: feat

#65 feat: #58/네비게이션 바 로그아웃 제외 완성
  src/app/(after-login)/dashboard/[dashboardid]/_components/DashboardIdSetter.tsx
  src/app/(after-login)/dashboard/[dashboardid]/layout.tsx
  src/app/(after-login)/mydashboard/layout.tsx
  src/app/(after-login)/mypage/layout.tsx
  src/components/common/modal/Modal.tsx
  src/components/layout/navbar/DashboardMenu.tsx
  src/components/layout/navbar/DashboardTitle.tsx
  src/components/layout/navbar/MemberList.tsx
  src/components/layout/sidebar/SideMenuItem.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/lib/apis/dashboard.ts
  src/lib/types.ts
Labels: fix, design, feat

#72 feat: #53/대시보드 상세 페이지 할 일 카드 레이아웃 및 할 일 상세 모달과 연결
  docs/STYLE_GUIDE.md
  next.config.mjs
  package-lock.json
  package.json
  src/app/(after-login)/dashboard/[dashboardid]/_components/DashboardColumn.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/TaskCard.tsx
  src/app/(after-login)/dashboard/[dashboardid]/layout.tsx
  src/app/(after-login)/dashboard/[dashboardid]/page.tsx
  src/app/(after-login)/mydashboard/layout.tsx
  src/app/(after-login)/mypage/layout.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/modal/task-detail/TaskDetail.tsx
  src/lib/apis/cardsApi.ts
  src/lib/apis/columnsApi.ts
  src/lib/apis/dashboardsApi.ts
  src/lib/apis/membersApi.ts
  src/lib/store/useTaskStore.ts
  src/lib/types.ts
  src/lib/utils/dateUtils.ts
Labels: refactor, design, feat

#76 버튼 컴포넌트 사이즈 prop 추가
  src/components/common/button/Button.tsx
  src/components/common/button/buttonStyles.tsx
Labels: refactor

#79 feat: #68/태그 & 태그 인풋 컴포넌트
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/TaskCard.tsx
  src/app/(after-login)/dashboard/[dashboardid]/page.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/TagInput.tsx
  src/components/common/modal/ModalProvider.tsx
  src/components/common/tag/TagList.tsx
  src/components/modal/create-task/CreateTaskModal.tsx
  src/components/modal/task-detail/TaskDetailModal.tsx
Labels: design, feat

#80 [feat]#63/페이지네이션 버튼
  src/components/common/pagenation-button/PagenationButton.tsx
  src/components/layout/navbar/Navbar.tsx
  src/lib/store/useAuthStore.ts
Labels: feat

#81 feat: #74/Auth 페이지 레이아웃 구현
  public/logo/logo_main.svg
  src/app/(before-login)/(without-navbar)/layout.tsx
  src/app/(before-login)/(without-navbar)/login/page.tsx
  src/app/(before-login)/(without-navbar)/signup/page.tsx
  src/components/common/button/buttonStyles.tsx
Labels: design, feat

#83 feat: #78/할 일 카드 모달 상단 레이아웃
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/TaskCard.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalProvider.tsx
  src/components/common/modal/modalData.ts
  src/components/common/user-icon/UserIcon.tsx
  src/components/modal/task-detail/ColumnNameTag.tsx
  src/components/modal/task-detail/TaskContentSection.tsx
  src/components/modal/task-detail/TaskDetailModal.tsx
  src/components/modal/task-detail/TaskInfoSection.tsx
  src/lib/store/useColumnStore.ts
Labels: design

#92 feat: #87/컬럼 추가 & 수정 모달
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/EditColumnButton.tsx
  src/app/(before-login)/(without-navbar)/login/page.tsx
  src/app/(before-login)/(without-navbar)/signup/page.tsx
  src/components/common/alert/AlertProvider.tsx
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/lib/apis/columnsApi.ts
  src/lib/store/useColumnStore.ts
Labels: design, feat

#95 feat: #91/초대하기 모달
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/EditColumnButton.tsx
  src/components/common/alert/AlertProvider.tsx
  src/components/common/modal/modalData.ts
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/create-dashboard/CreateDashboardModal.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/components/modal/invite/InviteModal.tsx
  src/lib/apis/dashboardsApi.ts
  src/lib/types.ts
  src/lib/utils/validationUtils.ts
Labels: feat

#96 refactor: #75/로그인 및 회원가입 페이지 리팩토링
  package-lock.json
  package.json
  src/app/(before-login)/(without-navbar)/layout.tsx
  src/app/(before-login)/(without-navbar)/login/page.tsx
  src/app/(before-login)/(without-navbar)/signup/page.tsx
  src/components/common/input/Input.tsx
  src/lib/utils/validationSchema.ts
Labels: refactor, feat

#97 design: #94/마이페이지 레이아웃
  public/icon/arrow_right_icon.svg
  src/app/(after-login)/mypage/_components/BackButton.tsx
  src/app/(after-login)/mypage/_components/PasswordSection.tsx
  src/app/(after-login)/mypage/_components/ProfileSection.tsx
  src/app/(after-login)/mypage/page.tsx
Labels: design, feat

#98 [feat] #19/할 일 생성 모달 레이아웃 구현
  public/icon/dropdown_icon.svg
  src/components/common/input/Input.tsx
  src/components/common/textarea/Textarea.tsx
  src/components/modal/create-task/CreateTaskModal.tsx
Labels: design, feat

#101 feat: #88/대시보드 상세 페이지 할 일 카드 무한 스크롤
  next.config.mjs
  src/app/(after-login)/dashboard/[dashboardid]/_components/AddTaskButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/dashboard/[dashboardid]/_components/EditColumnButton.tsx
  src/lib/apis/cardsApi.ts
Labels: feat

#102 feat: #22/사이드 바 페이지네이션 구현
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/mydashboard/layout.tsx
  src/app/(after-login)/mypage/layout.tsx
  src/components/layout/sidebar/SideMenuItem.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/layout/sidebar/index.tsx
  src/lib/apis/dashboardsApi.ts
  src/lib/hooks/useIntersection.ts
Labels: feat

#104 feat: #103/할 일 카드 모달 완료
  src/components/common/modal/MenuButton.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/textarea/Textarea.tsx
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/components/modal/task-detail/CommentCard.tsx
  src/components/modal/task-detail/CommentList.tsx
  src/components/modal/task-detail/TaskCommentSection.tsx
  src/components/modal/task-detail/TaskDetailModal.tsx
  src/lib/apis/cardsApi.ts
  src/lib/apis/commentsApi.ts
  src/lib/types.ts
Labels: design, feat

#105 refactor: #75/로그인, 회원가입 페이지 API 연결
  src/app/(before-login)/(without-navbar)/layout.tsx
  src/app/(before-login)/(without-navbar)/login/page.tsx
  src/app/(before-login)/(without-navbar)/signup/page.tsx
  src/components/common/alert/AlertProvider.tsx
  src/components/common/alert/alertData.ts
  src/lib/apis/authApi.ts
  src/lib/store/useAlertStore.ts
  src/lib/utils/validationSchema.ts
Labels: refactor

#106 refactor: #99/할 일 카드 모달 리팩토링
  src/components/modal/task-detail/TaskContentSection.tsx
  src/components/modal/task-detail/TaskDetailModal.tsx
  src/lib/utils/colorUtils.ts
Labels: refactor, design

#108 feat: #67/네비게이션 바 유저 메뉴 로그아웃 api 연결 & 로그인/로그아웃 시 리디렉트 & 실제 액세스 토큰으로 리퀘스트
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/dashboard/[dashboardid]/layout.tsx
  src/app/(after-login)/dashboard/[dashboardid]/page.tsx
  src/app/(after-login)/layout.tsx
  src/app/(after-login)/mydashboard/layout.tsx
  src/app/(after-login)/mypage/_components/ProfileSection.tsx
  src/app/(after-login)/mypage/layout.tsx
  src/app/(before-login)/(with-navbar)/page.tsx
  src/app/(before-login)/(without-navbar)/login/page.tsx
  src/app/(before-login)/layout.tsx
  src/components/common/alert/AlertProvider.tsx
  src/components/common/modal/MenuButton.tsx
  src/components/layout/navbar/UserMenu.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/create-dashboard/CreateDashboardModal.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/components/modal/invite/InviteModal.tsx
  src/components/modal/task-detail/CommentCard.tsx
  src/components/modal/task-detail/CommentList.tsx
  src/components/modal/task-detail/TaskCommentSection.tsx
  src/components/modal/task-detail/TaskDetailModal.tsx
  src/lib/apis/membersApi.ts
Labels: feat

#109 feat: #108/대시보드 수정 페이지 컴포넌트로 분리
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/BackButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/DashboardEditSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/InvitationSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/MemberSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/page.tsx
  src/app/(after-login)/mypage/page.tsx
Labels: feat

#111 feat: #110/대시보드 수정 페이지 일부 기능 구현
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/BackButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/DashboardEditSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/DeleteButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/InvitationCard.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/InvitationSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/InviteModalButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/MemberSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/page.tsx
  src/app/(after-login)/mypage/_components/BackButton.tsx
  src/components/common/pagenation-button/PagenationButton.tsx
  src/components/layout/navbar/MemberList.tsx
  src/components/layout/navbar/Navbar.tsx
  src/components/layout/sidebar/AddButton.tsx
  src/components/layout/sidebar/SideMenuHeader.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/layout/sidebar/index.tsx
  src/components/modal/create-dashboard/CreateDashboardModal.tsx
  src/lib/apis/dashboardsApi.ts
Labels: design, feat

#113 refactor: #112/나의 대시보드 페이지 컴포넌트 분리
  src/app/(after-login)/mydashboard/_components/DashboardListSection.tsx
  src/app/(after-login)/mydashboard/_components/InvitationSection.tsx
  src/app/(after-login)/mydashboard/page.tsx
Labels: refactor

#116 feat: #112/나의 대시보드 페이지 초대 부분 완료 및 대시보드 수정 페이지 구성원 부분 수정
  public/icon/search_icon.svg
  public/mydashboardPage/empty_invitation.svg
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/DeleteButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/InvitationSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/MemberSection.tsx
  src/app/(after-login)/mydashboard/_components/DashboardListSection.tsx
  src/app/(after-login)/mydashboard/_components/InvitationCard.tsx
  src/app/(after-login)/mydashboard/_components/InvitationSection.tsx
  src/components/common/pagination-button/PaginationButton.tsx
  src/components/modal/task-detail/CommentCard.tsx
  src/lib/apis/invitationsApi.ts
  src/lib/apis/membersApi.ts
Labels: refactor, design, feat

#117 feat: #107/계정관리 페이지 API 연결 및 유효성검사
  package-lock.json
  package.json
  src/app/(after-login)/mypage/_components/BackButton.tsx
  src/app/(after-login)/mypage/_components/PasswordSection.tsx
  src/app/(after-login)/mypage/_components/ProfileSection.tsx
  src/components/common/alert/AlertProvider.tsx
  src/components/common/alert/alertData.ts
  src/components/common/input/ImageInput.tsx
  src/components/layout/navbar/UserMenu.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/lib/apis/accountApi.ts
  src/lib/apis/imageApi.ts
  src/lib/store/useAlertStore.ts
Labels: refactor, feat
