Repository hyeonjiroh/Taskify, pull requests merged in 2025-04, with the labels that each got.

#118 feat: #112/나의 대시보드 페이지 내 대시보드 목록
  src/app/(after-login)/mydashboard/_components/AddDashboardButton.tsx
  src/app/(after-login)/mydashboard/_components/DashboardCard.tsx
  src/app/(after-login)/mydashboard/_components/DashboardListSection.tsx
  src/components/common/pagination-button/PaginationButton.tsx
Labels: refactor, design, feat

#120 feat: #119/할 일 수정 모달
  src/components/common/input/DateInput.tsx
  src/components/common/input/ImageInput.tsx
  src/components/common/input/TagInput.tsx
  src/components/common/modal/Modal.tsx
  src/components/modal/create-task/CreateTaskModal.tsx
  src/components/modal/edit-task/AssigneeDropdown.tsx
  src/components/modal/edit-task/ColumnDropdown.tsx
  src/components/modal/edit-task/EditTaskModal.tsx
  src/lib/apis/cardsApi.ts
Labels: refactor, design, feat

#121 [refactor] ImageInput token prop 추가
  src/components/common/input/ImageInput.tsx
  src/components/modal/edit-task/EditTaskModal.tsx
Labels: refactor

#125 docs: #0/Update README.md
  README.md
Labels: docs

#126 docs: #0/Update README.md
  README.md
Labels: docs

#127 docs: #0/Update README.md
  README.md
Labels: docs

#138 refactor: #137/api 함수 에러 처리 & data fetching 시 로딩, 에러 처리
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/DashboardEditSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/DeleteButton.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/InvitationCard.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/InvitationSection.tsx
  src/app/(after-login)/mydashboard/_components/InvitationCard.tsx
  src/components/common/alert/AlertProvider.tsx
  src/components/common/modal/MenuButton.tsx
  src/components/layout/navbar/UserMenu.tsx
  src/components/layout/sidebar/SideMenuList.tsx
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/create-dashboard/CreateDashboardModal.tsx
  src/components/modal/edit-task/AssigneeDropdown.tsx
  src/components/modal/edit-task/ColumnDropdown.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/components/modal/invite/InviteModal.tsx
  src/components/modal/task-detail/CommentCard.tsx
  src/components/modal/task-detail/CommentList.tsx
  src/components/modal/task-detail/TaskCommentSection.tsx
  src/components/modal/task-detail/TaskDetailModal.tsx
  src/lib/apis/cardsApi.ts
  src/lib/apis/columnsApi.ts
  src/lib/apis/commentsApi.ts
  src/lib/apis/dashboardsApi.ts
  src/lib/apis/invitationsApi.ts
  src/lib/apis/membersApi.ts
  src/lib/apis/usersApi.ts
Labels: refactor

#139 refactor: #133/로딩 스피너 추가
  package-lock.json
  package.json
  src/app/(after-login)/dashboard/[dashboardid]/_components/Column.tsx
  src/app/(after-login)/mypage/_components/ProfileSection.tsx
  src/components/common/input/ImageInput.tsx
  src/components/modal/create-task/CreateTaskModal.tsx
  src/components/modal/edit-task/EditTaskModal.tsx
Labels: refactor

#141 [refactor] #137/데이터 로딩 시 layout shift 방지
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/DashboardEditSection.tsx
  src/app/(after-login)/dashboard/[dashboardid]/edit/_components/InvitationSection.tsx
  src/components/layout/navbar/UserMenu.tsx
  src/components/modal/add-column/AddColumnModal.tsx
  src/components/modal/edit-task/AssigneeDropdown.tsx
  src/components/modal/edit-task/ColumnDropdown.tsx
  src/components/modal/editColumn/EditColumnModal.tsx
  src/components/modal/invite/InviteModal.tsx
  src/components/modal/task-detail/TaskCommentSection.tsx
  src/components/modal/task-detail/TaskDetailModal.tsx
Labels: refactor
